### ISSUE TITLE
belenios-tool still looks for threshold.json

### ISSUE THREAD

**Issue by millosolomillo** [glondu/belenios#25]
Hello,

Could you please update the package belenios-tool for Debian Buster?

When verifying or validating elections it throws an error as it still looks for threshold.json.

**Comment by glondu** [comment]
Debian Buster is "stable". It is not meant to be updated, except in some special cases.

Making a backport can be problematic because of the old version of OCaml in Buster.

What I can suggest you is to use an unstable (or testing) chroot. It may even be possible that the unstable binary works directly on a buster system.

**Comment by glondu** [comment]
And of course, you can still build from sources, using opam (and the opam-bootstrap.sh script).

**Comment by Jean-Baptiste-Lasselle** [comment]
And you can even run it as a standalone executable, as proved with version 1.13 of belenios, see https://github.com/glondu/belenios/issues/7#issuecomment-808359005
