### ISSUE TITLE
HTTP Unauthenticated Error Response

### ISSUE THREAD

**Issue by albanbruder** [glondu/belenios#43]
Since 1.16 Belenios responds with an 401 error code when trying to access an admin page as an unauthenticated user. The response body looks something likes the following: `Error: Ocsigen_cohttp.Ocsigen_http_error(0, 324098644)`

E.g: https://belenios.loria.fr/draft/election?uuid=QZHqeNr1sx1m6B

In the previous versions this was an 403 error code and a Forbidden page was displayed to the user.

Maybe we could make this more user friendly. E.g. by displaying another error message or by redirecting to the login page?

**Comment by glondu** [comment]
There are two issues in this report:

1. the HTTP response code is incorrect (401 instead of 403)
2. the error page is not friendly

I've fixed both (in the master branch). I've fixed 2 by showing an explicit (localized) error page, with the generic footer that links to the "Administer elections" page, where one can log in. It feels wrong to directly redirect to the login page in all cases.
