### ISSUE TITLE
Possible vulnerability to election faking?

### ISSUE THREAD

**Issue by Vadiml1024** [glondu/belenios#48]
Is there any plans to address this:   https://hal.inria.fr/hal-02928953/document

**Comment by glondu** [comment]
It has been addressed in Belenios 1.17 :-)

**Comment by Vadiml1024** [comment]
Thank you, Stéphane for the info,
would you mind, please, pointing to a specific patch - my Ocaml is VERY Rusty :-(

**Comment by glondu** [comment]
The fix was part of the "crypto-v1" branch, which aimed at fixing several theoretical bugs like the one you mention, that couldn't be fixed in a backward-compatible way. The branch has been merged in d267ee3c410855a0936f8f435f9961022ab885e0. The specific issue you raise was addressed by adding a "full" description of the group in zero-knowledge proofs, so that the generator cannot be changed (without changing the source code). Actually, this gives less flexibility in the code but we don't think this flexibility is actually needed.

**Comment by Vadiml1024** [comment]
Hi Stéphane, thank you for the pointer

Le ven. 7 janv. 2022 à 07:27, Stéphane Glondu ***@***.***> a
écrit :
